### PR TITLE
Use the new watchApi introduced in typescript@2.7

### PR DESCRIPTION
**Pull request by sheetalkamat**
This is upgrade from #74 to ensure backward compatibility with previous typescript versions

### CODE REVIEW

**Comment by jrieken** [comment]
Hm... I have noticed that getting this version of gulp-tsb up and running is significantly slower than tsc in watch mode (160sec vs 50sec). Any idea why?

**Comment by jrieken** [comment]
My bugger plan is that I want those changes and I wanna throw out the old. That logic we can keep in the 2.x branch, go to version 3.x on master and support the new world only. My plan would be to merge this PR and do further work on master but first I wanna understand if there is fundamental difference that explains why the startup-perf is so different...

**Comment by sheetalkamat** [comment]
> Hm... I have noticed that getting this version of gulp-tsb up and running is significantly slower than tsc in watch mode (160sec vs 50sec). Any idea why?

Which source did you run this on, I can try this on that same source and see whats going on.

**Comment by jrieken** [comment]
I have used the `watch-client` target after sym-linking the new version of gulp-tsb. Because of memory flags use `npm run gulp watch-client`

**Comment by jrieken** [comment]
Sorry false alarm... Wasn't able to reproduce anymore. I'll proceed with merging this PR

**Pull request merged**
